name: nVerse

main: com.niccholaspage.nVerse.nVerse

version: 0.1

load: startup

commands:
  nVerse:
    usage: /<command>
    description: nVerse's command
    aliases:
    - nv

permissions:
  nVerse.command.createworld:
    description: Allows you to create a world