name: nVerse

main: com.niccholaspage.nVerse.nVerse

version: 0.1

commands:
  nVerse:
    usage: /<command>
    description: nVerse's command
    aliases:
    - nv

permissions:
  nVerse.command.create:
    description: Allows you to create a world
  nVerse.command.goto:
    description: Allows you to teleport to a world
  nVerse.command.help:
    description: Allows you to view help
  nVerse.command.list:
    description: Allows you to view every world
  nVerse.command.remove:
    description: Allows you to remove worlds
  nVerse.bypass:
    description: Allows you to bypass gamemode switches
  nVerse.command.*:
    children:
      nVerse.command.create
      nVerse.command.goto
      nVerse.command.help
      nVerse.command.list
      nVerse.command.remove
  nVerse.admin:
    children:
      nVerse.command.*
      nVerse.bypass