name: nVerse

main: com.niccholaspage.nVerse.nVerse

version: 0.1

commands:
  nVerse:
    usage: /<command>
    description: nVerse's command
    aliases:
    - nv

permissions:
  nVerse.command.create:
    description: Allows you to create a world
  nVerse.command.goto:
    description: Allows you to teleport to a world
  nVerse.command.help:
    description: Allows you to view help
  nVerse.command.list:
    description: Allows you to view every world
  nVerse.command.remove:
    description: Allows you to remove worlds
  nVerse.command.?:
    description: Allows you to view help
  nVerse.command.reload:
    description: Allows you to reload the configuration
  nVerse.bypass:
    description: Allows you to bypass gamemode switches
  nVerse.command.*:
    children:
      nVerse.command.create: true
      nVerse.command.goto: true
      nVerse.command.?: true
      nVerse.command.list: true
      nVerse.command.remove: true
      nVerse.command.reload: true
  nVerse.admin:
    children:
      nVerse.command.*: true
      nVerse.bypass: true